# Deployment, Service, HPA를 하나의 파일로 통합하여 관리 편의성을 높입니다.
# EKS 클러스터에 배포할 Comment 마이크로서비스의 설계도입니다.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment-service-deployment
  namespace: comment-service
  labels:
    app: comment-service
spec:
  replicas: 1 # HPA가 동적으로 스케일링하므로 기본값 1로 설정
  selector:
    matchLabels:
      app: comment-service
  template:
    metadata:
      labels:
        app: comment-service
    spec:
      serviceAccountName: comment-service-sa
      containers:
        - name: comment-service
          image: 245040175511.dkr.ecr.ap-northeast-2.amazonaws.com/comment-service:latest # CI/CD 파이프라인에서 최신 이미지로 교체됩니다.
          ports:
            - containerPort: 8083
          env:
            - name: ENVIRONMENT
              value: "production"
          envFrom:
            - secretRef:
                name: rds-credentials
            - secretRef:
                name: comment-parameters
          resources:
            requests:
              memory: "512Mi"
              cpu: "300m"
            limits:
              memory: "1Gi"
              cpu: "700m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8083
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 8083
            initialDelaySeconds: 15
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: comment-service
  namespace: comment-service
  labels:
    app: comment-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-eip-allocations: eipalloc-02507578dd1188916
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-subnets: subnet-07d6dfa6e7328bddc,subnet-0752978f0a9e90e3c
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  selector:
    app: comment-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8083
  type: LoadBalancer
# HPA는 나중에 Metrics Server 설치 후 사용 예정
# ---
# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: comment-service-hpa
#   namespace: comment-service
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: comment-service-deployment
#   minReplicas: 1
#   maxReplicas: 3
#   metrics:
#     - type: Resource
#       resource:
#         name: cpu
#         target:
#           type: Utilization
#           averageUtilization: 70
