# ServiceAccount (IAM Role for Service Account)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: comment-service-sa
  namespace: comment-service
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::245040175511:role/eks-pod-management-role
---
# SecretStore for Secrets Manager
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: comment-service
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-2
      auth:
        jwt:
          serviceAccountRef:
            name: comment-service-sa
---
# SecretStore for Parameter Store
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-parameter-store
  namespace: comment-service
spec:
  provider:
    aws:
      service: ParameterStore
      region: ap-northeast-2
      auth:
        jwt:
          serviceAccountRef:
            name: comment-service-sa
---
# ExternalSecret for RDS Credentials (Secrets Manager)
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rds-credentials
  namespace: comment-service
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: rds-credentials
    creationPolicy: Owner
  data:
    - secretKey: DB_USER
      remoteRef:
        key: rds-db-credentials/db-KTXPOD7NONJB6GR2JY3H6QPEAY/admin/1757384998686
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: rds-db-credentials/db-KTXPOD7NONJB6GR2JY3H6QPEAY/admin/1757384998686
        property: password
---
# ExternalSecret for App Parameters (Parameter Store)
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: comment-parameters
  namespace: comment-service
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: SecretStore
  target:
    name: comment-parameters
    creationPolicy: Owner
  data:
    - secretKey: access_key
      remoteRef:
        key: /Comment_access_key
    - secretKey: access_key_id
      remoteRef:
        key: /Comment_access_key_id
    - secretKey: region
      remoteRef:
        key: /Comment_region
    # RDS connection info (added to Parameter Store)
    - secretKey: DB_HOST
      remoteRef:
        key: /Comment_DB_HOST
    - secretKey: DB_PORT
      remoteRef:
        key: /Comment_DB_PORT
    - secretKey: DB_NAME
      remoteRef:
        key: /Comment_DB_NAME
    - secretKey: DATABASE_URL
      remoteRef:
        key: /Comment_DATABASE_URL
    # Application configuration
    - secretKey: SECRET_KEY
      remoteRef:
        key: /Comment_SECRET_KEY
    - secretKey: COGNITO_USER_POOL_ID
      remoteRef:
        key: /Comment_COGNITO_USER_POOL_ID
    - secretKey: COGNITO_REGION
      remoteRef:
        key: /Comment_COGNITO_REGION
    - secretKey: COGNITO_CLIENT_ID
      remoteRef:
        key: /Comment_COGNITO_CLIENT_ID
    - secretKey: JWT_SECRET_KEY
      remoteRef:
        key: /Comment_JWT_SECRET_KEY
    - secretKey: POST_SERVICE_URL
      remoteRef:
        key: /Comment_POST_SERVICE_URL
